name: Submission

on:
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: read

jobs:
  submission:
    name: Automated submission checks
    uses: web-programming-contest/web-programming-ci-utils/.github/workflows/submission.yml@bf8d1d8c56029d27f071050f0d5690a33825e9b7
    with:
      utils_repository: web-programming-contest/web-programming-ci-utils
      utils_ref: "bf8d1d8c56029d27f071050f0d5690a33825e9b7"
